package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"graph-gateway/graph/model"
	"graph-gateway/protos/comms"
)

// ChannelStatuses is the resolver for the channel_statuses field.
func (r *channelStatusResolver) ChannelStatuses(ctx context.Context, obj *comms.ChannelStatus, data []*model.ChannelStatuses) error {
	for i := 0; i < len(data); i++ {
		obj.ChannelStatuses[data[i].Key] = data[i].Value
	}
	return nil
}

// ChannelStatus returns ChannelStatusResolver implementation.
func (r *Resolver) ChannelStatus() ChannelStatusResolver { return &channelStatusResolver{r} }

type channelStatusResolver struct{ *Resolver }
