// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"graph-gateway/protos/comms"
)

type ChannelStatuses struct {
	Key   string                `json:"key"`
	Value *comms.CallbackStatus `json:"value"`
}
